name: Windows Installer Publish
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    if: "contains(github.event.head_commit.message, 'bump')"
    name: Build the Inno Setup Installer
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Publish
        run: dotnet publish ./PrintQuotesCalculator/PrintQuotesCalculator.csproj -c Release -o ./PrintQuotesCalculator.Deploy/ApplicationFiles

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: ./PrintQuotesCalculator.Deploy/InstallerSetupScript.iss
          options: /DMyAppVersion=${{ steps.package_version.outputs.version }}

      - name: Get Version
        id: package_version
        uses: KageKirin/get-csproj-version@v0
        with:
          file: ./PrintQuotesCalculator/PrintQuotesCalculator.csproj

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          files: ./PrintQuotesCalculator.Deploy/Output/pqcsetup-${{ steps.package_version.outputs.version }}.exe
          tag_name: v${{ steps.package_version.outputs.version }}
          name: v${{ steps.package_version.outputs.version }}
          generate_release_notes: true
          make_latest: true
          
